# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-13 12:29
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0015_auto_20160421_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSLogin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('show_logout', models.BooleanField(default=True, help_text='If the user is allready logged-in:  if checked a log out button is shown. else the plugin is invisible.', verbose_name='Show logout')),
                ('cms_page', cms.models.fields.PageField(blank=True, help_text='If left empty the user stays on the current page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Success target')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSLogout',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('cms_page', cms.models.fields.PageField(blank=True, help_text='If left empty the user stays on the current page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Success target')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
